#!name=Apple WLOC Location Spoofer
#!desc=Modify the coordinates returned by Apple's network-based location service (WiFi/cell) | Shortcuts (recommended): Set Location https://www.icloud.com/shortcuts/182f3a014597468eb1b15b99261cdf22 Clear & Restore Location https://www.icloud.com/shortcuts/0352d53ed79849d382f50e9adf050662 | Picker page: https://wloc-spoofer-selfhost.gpt5383.workers.dev/
#!author=Yu9191 Rewrite
#!homepage=https://github.com/zonecloud6-ops/wloc-spoofer-en


[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/zonecloud6-ops/wloc-spoofer-en/refs/heads/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/zonecloud6-ops/wloc-spoofer-en/refs/heads/main/dist/wloc-settings.js


[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com

